# -*- coding: utf-8 -*-
"""covid_testingDT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIezpvp0ZdZ2hKN5Bz6pKY2iV-Ie34j_
"""

list1 = []
a = 1 
b  = 2
list1.extend([a,b,b,a])
list1
len(list1)

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv('/content/sample_data/covidtesting-3.csv')
len(data)

y = data[['testing_required']].copy()
y

X = data.drop(columns = ['testing_required'])
X.head()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.7,random_state=42)

covid_classifier = DecisionTreeClassifier(max_leaf_nodes=10,random_state=0)
covid_classifier.fit(X_train,y_train)

y_predicted = covid_classifier.predict(X_test)
y_predicted

accuracy_score(y_test,y_predicted)*100

import pickle
pkl_filename = "model.pkl"
with open(pkl_filename, 'wb') as file:  
    pickle.dump(covid_classifier, file)

with open(pkl_filename, 'rb') as file:  
    covid_classifier_pkl = pickle.load(file)

covid_classifier_pkl

import numpy as np
sample_neg = [1	,1	,0	,0	,0	,0	,0]
sample_pos = [1,	0,	1,	0,	0,	1,	0]
arr_neg = np.array(sample_neg)
arr_pos = np.array(sample_pos)

prediction = covid_classifier_pkl.predict(arr_neg.reshape(-1,7))
prediction

prediction = covid_classifier_pkl.predict(arr_pos.reshape(-1,7))
prediction

